### ISSUE TITLE
Fix webpack source maps

### ISSUE THREAD

**Issue by kevmo314** [kevmo314/canigraduate.uchicago.edu#27]
The source maps are not working. Not sure if it's webpack's fault. Maybe we should just stop using webpack all together as it's kind of a giant mess anyways...

**Comment by maths22** [comment]
I may take a look at this. (I enjoy working with webpack.  I must hate myself or something.)

Is the old frontend code still in use at all, or just the vue one?

**Comment by kevmo314** [comment]
Thanks! Just the vue frontend is in use, the old one is still there because there's a couple chunks of logic that haven't been copied over but will probably be deleted soon.

**Comment by kevmo314** [comment]
It seems like this was fixed magically with the upgrade to Webpack 4. Hooray!
